name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger
    inputs:
      theme_name:
        description: 'Name of the keyboard theme'
        required: true
        default: 'Custom Theme'
      creator:
        description: 'Creator of the theme'
        required: false
        default: 'Anonymous'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ElEmberator/KeyboardThemeMaker
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Sign Release APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "33.0.1"
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-signed
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}
        
    - name: Generate APK metadata
      run: |
        echo "APK_NAME=${{ inputs.theme_name || 'zozo' }}-$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.APK_NAME }}
        tag_name: v${{ github.run_number }}
        files: ${{ steps.sign_app.outputs.signedReleaseFile }}
        body: |
          # ${{ inputs.theme_name || 'zozo' }} Keyboard Theme
          
          Created by: ${{ inputs.creator || 'Anonymous' }}
          Build Date: ${{ env.BUILD_DATE }}
          
          ## Installation
          1. Download the APK
          2. Install on your Android device
          3. Open Settings > System > Languages & Input > Virtual Keyboard
          4. Enable the keyboard theme